name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t servico-vendas .

      - name: Deploy (placeholder)
        run: echo "Deploy do servico de vendas concluido com sucesso"
